name: Windows autobuild
on:
  push:
    branches: [ 'dev', 'autobuild' ]
    paths-ignore: [ '*.md', '*.json', '*.png' ]
  pull_request:
    branches: [ 'dev', 'autobuild' ]
    paths-ignore: [ '*.md', '*.json', '*.png' ]

jobs:
  autobuild:
    uses: EnterVPL/mkxp-z/.github/workflows/windows-autobuild-template.yml@dev
    secrets:
      STEAM_SDK_TOKEN: ${{ matrix.target.steam_secret_name != 'empty' && secrets.STEAM_SDK_TOKEN || ''}}
    with:
      icon_file: ${{ matrix.target.icon }}
      steam_appid: ${{ matrix.target.steam_appid }}
    strategy:
      matrix:
        target:
          - version: "Steam Playtest"
            icon: "./icons/TESTICON.png"
          - version: "Steam Release"
            steam_appid: "1964650"
            icon: "icons/BAASE_ICON.png"


# Todo Linux