name: Windows autobuild
on:
  push:
    branches: [ 'dev', 'autobuild' ]
    paths-ignore: [ '*.md', '*.json', '*.png' ]
  pull_request:
    branches: [ 'dev', 'autobuild' ]
    paths-ignore: [ '*.md', '*.json', '*.png' ]

jobs:
  autobuild:
    uses: EnterVPL/mkxp-z/.github/workflows/windows-autobuild-template.yml@dev
    secrets:
      STEAM_APPID: ${{ matrix.target.steam_secret_name != 'empty' && secrets[matrix.target.steam_secret_name] || ''}}
      STEAM_SDK_TOKEN: ${{ matrix.target.steam_secret_name != 'empty' && secrets.STEAM_SDK_TOKEN || ''}}
    with:
      icon_file: ${{ matrix.target.icon }}
    strategy:
      matrix:
        target:
          - version: "Steam Playtest"
            icon: "./assets/TESTICON.png"
            steam_secret_name: "empty"
          - version: "Steam Release"
            icon: "./assets/icon.png"
            steam_secret_name: "STEAM_APPID"


# Todo Linux