# I have no idea what I'm doing 
# I have more idea but I don't know what's it going
name: Windows autobuild template

on:
  workflow_call:
    secrets:
      STEAM_SDK_TOKEN:
        required: false
    inputs:
      icon_file:
        type: string
        default: ""
      viewport_w_offset:
        type: number
        default: 3
      steam_appid:
        type: string
        default: ""
        

jobs:
  build-windows:
    name: Windows
    runs-on: windows-latest
    env:
      LANG: "en_US.UTF-8"

    steps:
      - uses: benjlevesque/short-sha@v3.0
        id: short-sha
        with:
          length: 7

      - uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          update: true
          install: >-
            base-devel
            git
            ruby
            vim
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-meson
            mingw-w64-x86_64-autotools
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-imagemagick


      - name: Checkout repository
        uses: actions/checkout@v6

      - uses: actions/cache@v5
        with:
          path: |
            windows/build-mingw64
            windows/downloads
          key: win-${{ hashFiles('windows/Makefile') }}

      - name: Prepare files
        env:
          REPLACE_OFFSET_COMMAND: "s/static const int viewpWOffset\\s*=\\s*[0-9]\\+/static const int viewpWOffset"
          TILEMAP_PATH: ${{github.workspace}}/src/display/tilemap.cpp
        shell: msys2 {0}
        if: inputs.icon_file != ''
        run: |
          echo "Start copying icon ${{ inputs.icon_file }}..."
          cp -f "${{ inputs.icon_file }}" "./assets/icon.png" || true
          mkdir -p /tmp
          echo "Convert to *. ico file"
          convert ${{ inputs.icon_file }} /tmp/icon.ico
          cp -f /tmp/icon.ico "./windows/icon.ico"
          echo "👍🏻 it was fast. Now, change vieportW offset"
          echo "DONE"

#          sed -i "${{env.REPLACE_OFFSET_COMMAND}} = ${{inputs.viewport_w_offset}}/" "${{env.TILEMAP_PATH}}"
#          echo "Now offset is"
#          echo grep -oP 'static const int viewpWOffset\s*=\s*\K[0-9]+' "${{env.TILEMAP_PATH}}"


      - name: Checkout private steam sdk repo
        uses: actions/checkout@v6
        env:
          steam_id: ${{inputs.steam_appid}}
        if: env.steam_id != ''
        with:
          repository: ${{ secrets.STEAM_SDK_REPO }}
          token: ${{ secrets.STEAM_SDK_TOKEN || ''}}
          path: ${{ github.workspace }}/steam_sdk

      - name: Build all dependencies
        shell: msys2 {0}
        run: |
          cd windows
          make

      - name: Build exe
        shell: msys2 {0}
        env:
          STEAM_PATH: $(cygpath -u "${{ github.workspace }}/steam_sdk")
        run: |
          source windows/vars.sh
          rm -rf build
          
          MESON_FLAGS="-Duse_miniffi=true"
          
          if [ -n "${{ inputs.steam_appid }}" ]; then
            echo "Steam AppID detected. Adding Steamworks support."
            echo "Steam path: ${{env.STEAM_PATH}}"
            echo "Steam ID: ${{inputs.steam_appid}}"
            STEAM_PATH=$(cygpath -u "${{ github.workspace }}/steam_sdk")
            MESON_FLAGS="$MESON_FLAGS -Dsteamworks_path=${{env.STEAM_PATH}} -Dsteam_appid=${{ inputs.steam_appid }}"
          else
            echo "No Steam AppID provided. Compiling without Steamworks."
          fi
          
          meson setup build $MESON_FLAGS
          
          cd build
          ninja
          strip ./mkxp-z.exe

      - name: Prepare archive
        shell: msys2 {0}
        run: |
          mkdir build/artifact
          cd build/artifact
          cp /mingw64/bin/zlib1.dll .
          cp ../../windows/build-mingw64/bin/x64-msvcrt-ruby310.dll .
          cp -r ../../windows/build-mingw64/lib/ruby/3.1.0 .
          mv ./3.1.0 ./stdlib
          cp ../mkxp-z.exe .
          cp ../../mkxp.json .
          cp -r ../../scripts .
          cp ../../assets/LICENSE.mkxp-z-with-https.txt .
          
          if [ -n "${{ inputs.steam_appid }}" ]; then
            echo "Steam AppID detected. Copying Steam libraries..."
            STEAM_PATH=$(cygpath -u "${{ github.workspace }}/steam_sdk")
            cp ../steam_mkxp-z.exe .
            cp $STEAM_PATH/steam_api64.dll .
          else
            echo "No Steam AppID provided. Skipping Steam libraries."
          fi

      - name: Check for DLLs missing from the artifact
        shell: msys2 {0}
        run: |
          cd build/artifact
          error_flag=

          for file in *.exe *.dll
          do
            ldd_output="$(ldd "$file")"
            echo "$file"
            echo "$ldd_output"

            while IFS= read -r line
            do
              dll_name="$(echo "$line" | sed -e 's/=>/|/g' | cut -d '|' -f 1 | sed -e 's/^[ \t]*//g' -e 's/[ \t]*$//g')"
              dll_location="$(echo "$line" | sed -e 's/=>/|/g' | cut -d '|' -f 2 | sed -e 's/^[ \t]*//g' -e 's/[ \t]*$//g')"
              if [[ "$dll_location" = 'not found'* ]] || [[ "$dll_location" = '/mingw64/bin/'* ]] || [[ "$dll_location" = '/mingw64/lib/'* ]] || [[ "$dll_location" = '/mingw64/usr/bin/'* ]] || [[ "$dll_location" = '/mingw64/usr/lib/'* ]]
              then
                error_flag=1
                echo "::error::$dll_name is missing from the artifact"
              fi
            done <<< "$ldd_output"
          done

          if [ -n "$error_flag" ]
          then
            exit 1
          fi

      - uses: actions/upload-artifact@v7
        with:
          name: mkxp-z.windows.${{github.event_name == 'pull_request' && format('PR{0}', github.event.number) || github.ref_name}}-${{steps.short-sha.outputs.sha}}
          path: build/artifact
